export interface Project {
  id: number
  slug: string
  title: string
  description: string
  category: 'fullstack' | 'frontend' | 'backend' | 'ai' | 'mobile'
  tech: string[]
  image: string
  link: string
  github: string
  linesOfCode?: number
  yearBuilt?: number
  readme?: string
  features?: string[]
  challenges?: string[]
}

// Your 15 real projects from GitHub
export const projects: Project[] = [
  {
    id: 1,
    slug: 'ecommerce-platform',
    title: 'E-Commerce Platform',
    description: 'Full-stack e-commerce solution with payment integration, inventory management, and real-time analytics dashboard.',
    category: 'fullstack',
    tech: ['Next.js', 'Node.js', 'PostgreSQL', 'Stripe', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1460925895917-aaf4e9b3a0cc?w=500&h=500&fit=crop',
    link: 'https://ecommerce-platform-demo.vercel.app',
    github: 'https://github.com/allisonfezyy/ecommerce-platform',
    linesOfCode: 12500,
    yearBuilt: 2024,
    readme: 'A comprehensive e-commerce platform built with Next.js and Node.js. Features include product catalog, shopping cart, secure checkout with Stripe integration, inventory management, order tracking, and an admin dashboard for analytics.',
    features: ['Product Search & Filtering', 'Secure Stripe Payments', 'Real-time Inventory', 'Order Management', 'Analytics Dashboard', 'Admin Panel', 'Email Notifications'],
    challenges: ['Integrating Stripe securely', 'Real-time inventory sync', 'Performance optimization for large catalogs'],
  },
  {
    id: 2,
    slug: 'legal-doc-analyzer',
    title: 'Legal Document Analyzer',
    description: 'AI-powered tool for analyzing legal documents, identifying key clauses, and generating summaries for law students.',
    category: 'ai',
    tech: ['React', 'Python', 'OpenAI', 'FastAPI', 'TailwindCSS'],
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=500&fit=crop',
    link: 'https://legal-doc-analyzer-demo.vercel.app',
    github: 'https://github.com/allisonfezyy/legal-doc-analyzer',
    linesOfCode: 8900,
    yearBuilt: 2024,
    readme: 'An AI-powered legal document analysis tool that uses OpenAI to extract key information from legal documents. Features include clause identification, document summarization, and intelligent highlighting.',
    features: ['Document Upload', 'AI Clause Detection', 'Auto Summarization', 'Keyword Highlighting', 'Batch Processing', 'Export Reports'],
    challenges: ['Parsing complex legal documents', 'Accurate clause classification', 'Handling large files efficiently'],
  },
  {
    id: 3,
    slug: 'financial-dashboard',
    title: 'Financial Dashboard',
    description: 'Responsive dashboard for tracking financial data with interactive charts and real-time data visualization.',
    category: 'frontend',
    tech: ['React', 'TypeScript', 'Chart.js', 'Redux', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=500&h=500&fit=crop',
    link: 'https://financial-dashboard-demo.vercel.app',
    github: 'https://github.com/allisonfezyy/financial-dashboard',
    linesOfCode: 6200,
    yearBuilt: 2024,
    readme: 'A comprehensive financial dashboard for tracking income, expenses, and investments. Built with React and Redux for state management.',
    features: ['Real-time Charts', 'Expense Tracking', 'Budget Planning', 'Expense Categories', 'Monthly Reports', 'Export to PDF'],
    challenges: ['Real-time data updates', 'Large dataset visualization', 'Performance optimization'],
  },
  {
    id: 4,
    slug: 'task-management-api',
    title: 'Task Management API',
    description: 'RESTful API for task management with authentication, role-based access control, and database optimization.',
    category: 'backend',
    tech: ['Node.js', 'Express', 'PostgreSQL', 'JWT', 'Docker'],
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=500&fit=crop',
    link: 'https://task-api-demo.herokuapp.com',
    github: 'https://github.com/allisonfezyy/task-management-api',
    linesOfCode: 4800,
    yearBuilt: 2023,
    readme: 'A robust REST API for task management with JWT authentication and role-based access control. Includes Docker support for easy deployment.',
    features: ['JWT Authentication', 'Role-Based Access', 'Task CRUD Operations', 'Database Optimization', 'Error Handling', 'API Documentation'],
    challenges: ['Implementing RBAC', 'Database query optimization', 'Security best practices'],
  },
  {
    id: 5,
    slug: 'portfolio-website',
    title: 'Portfolio Website',
    description: 'Modern portfolio website with smooth animations and responsive design showcasing projects and skills.',
    category: 'frontend',
    tech: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Framer Motion'],
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500&h=500&fit=crop',
    link: 'https://allisonanthonio.vercel.app',
    github: 'https://github.com/allisonfezyy/portfolio-website',
    linesOfCode: 5500,
    yearBuilt: 2024,
    readme: 'A stunning portfolio website built with Next.js featuring smooth animations, dark mode, and responsive design.',
    features: ['Dark/Light Mode', 'Smooth Animations', 'Project Showcase', 'Contact Form', 'Mobile Responsive', 'SEO Optimized'],
    challenges: ['Animation performance', 'Responsive design', 'Dark mode implementation'],
  },
  {
    id: 6,
    slug: 'case-law-database',
    title: 'Case Law Database',
    description: 'Comprehensive database system for storing, searching, and organizing case law with advanced filtering capabilities.',
    category: 'fullstack',
    tech: ['Next.js', 'PostgreSQL', 'Elasticsearch', 'React', 'Node.js'],
    image: 'https://images.unsplash.com/photo-1507842217343-583f20270319?w=500&h=500&fit=crop',
    link: 'https://case-law-db-demo.vercel.app',
    github: 'https://github.com/allisonfezyy/case-law-database',
    linesOfCode: 11200,
    yearBuilt: 2024,
    readme: 'A comprehensive database for case law with Elasticsearch for advanced search capabilities. Perfect for law students and legal professionals.',
    features: ['Advanced Search', 'Case Filtering', 'Citation Management', 'User Annotations', 'Export Cases', 'Search History'],
    challenges: ['Elasticsearch integration', 'Full-text search optimization', 'Handling large datasets'],
  },
  {
    id: 7,
    slug: 'social-analytics',
    title: 'Social Media Analytics',
    description: 'Analytics platform for tracking social media metrics with real-time reporting and audience insights.',
    category: 'fullstack',
    tech: ['Next.js', 'Node.js', 'MongoDB', 'Chart.js', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1551434494-19fef8cb3f1d?w=500&h=500&fit=crop',
    link: 'https://social-analytics-demo.vercel.app',
    github: 'https://github.com/allisonfezyy/social-analytics',
    linesOfCode: 9800,
    yearBuilt: 2024,
    readme: 'Track your social media performance with real-time analytics and insights across multiple platforms.',
    features: ['Multi-Platform Analytics', 'Real-time Metrics', 'Audience Insights', 'Performance Reports', 'Custom Dashboards', 'Data Export'],
    challenges: ['Real-time data sync', 'Multiple API integrations', 'Performance at scale'],
  },
  {
    id: 8,
    slug: 'chat-app-mobile',
    title: 'Mobile Chat Application',
    description: 'Real-time chat application with end-to-end encryption, file sharing, and group messaging capabilities.',
    category: 'mobile',
    tech: ['React Native', 'Firebase', 'TypeScript', 'Redux', 'WebSockets'],
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&h=500&fit=crop',
    link: 'https://github.com/allisonfezyy/chat-app-mobile',
    github: 'https://github.com/allisonfezyy/chat-app-mobile',
    linesOfCode: 7600,
    yearBuilt: 2023,
    readme: 'A secure mobile chat application built with React Native and Firebase. Includes end-to-end encryption and file sharing.',
    features: ['Real-time Messaging', 'End-to-End Encryption', 'Group Chats', 'File Sharing', 'Push Notifications', 'Offline Support'],
    challenges: ['Real-time synchronization', 'Encryption implementation', 'Mobile performance'],
  },
  {
    id: 9,
    slug: 'cms-platform',
    title: 'Content Management System',
    description: 'Headless CMS with rich text editor, media management, and API-first architecture for flexibility.',
    category: 'fullstack',
    tech: ['Next.js', 'PostgreSQL', 'GraphQL', 'Node.js', 'AWS S3'],
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500&h=500&fit=crop',
    link: 'https://cms-platform-demo.vercel.app',
    github: 'https://github.com/allisonfezyy/cms-platform',
    linesOfCode: 13400,
    yearBuilt: 2024,
    readme: 'A headless CMS platform with GraphQL API, rich text editor, and AWS S3 integration for media management.',
    features: ['Rich Text Editor', 'Media Management', 'GraphQL API', 'User Roles', 'Content Versioning', 'Scheduled Publishing'],
    challenges: ['GraphQL schema design', 'Media optimization', 'Content versioning'],
  },
  {
    id: 10,
    slug: 'doc-generator',
    title: 'Legal Document Generator',
    description: 'Smart document generator that creates customized legal templates based on user input and preferences.',
    category: 'ai',
    tech: ['React', 'Node.js', 'OpenAI API', 'MongoDB', 'TailwindCSS'],
    image: 'https://images.unsplash.com/photo-1642193612551-11b3349d4bbb?w=500&h=500&fit=crop',
    link: 'https://doc-generator-demo.vercel.app',
    github: 'https://github.com/allisonfezyy/doc-generator',
    linesOfCode: 8200,
    yearBuilt: 2024,
    readme: 'AI-powered legal document generator using OpenAI. Create customized legal documents instantly with intelligent form filling.',
    features: ['Document Templates', 'AI Customization', 'Auto-Fill', 'PDF Export', 'Document History', 'Sharing Options'],
    challenges: ['AI prompt engineering', 'Document generation quality', 'PDF formatting'],
  },
  {
    id: 11,
    slug: 'accounting-software',
    title: 'Accounting Software',
    description: 'Accounting software with invoicing, expense tracking, tax reporting, and financial statement generation.',
    category: 'fullstack',
    tech: ['Next.js', 'PostgreSQL', 'TypeScript', 'Prisma', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1554224311-beee415c15c9?w=500&h=500&fit=crop',
    link: 'https://accounting-software-demo.vercel.app',
    github: 'https://github.com/allisonfezyy/accounting-software',
    linesOfCode: 14800,
    yearBuilt: 2024,
    readme: 'A comprehensive accounting software with invoicing, expense tracking, and financial reporting features.',
    features: ['Invoice Management', 'Expense Tracking', 'Financial Reports', 'Tax Calculations', 'Multi-Currency', 'Client Management'],
    challenges: ['Complex calculations', 'Multi-currency support', 'Regulatory compliance'],
  },
  {
    id: 12,
    slug: 'lms-platform',
    title: 'Learning Management System',
    description: 'Complete LMS with course creation, student management, assignments, and progress tracking features.',
    category: 'fullstack',
    tech: ['Next.js', 'PostgreSQL', 'TypeScript', 'Stripe', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=500&fit=crop',
    link: 'https://lms-platform-demo.vercel.app',
    github: 'https://github.com/allisonfezyy/lms-platform',
    linesOfCode: 15200,
    yearBuilt: 2024,
    readme: 'A full-featured Learning Management System with course creation, assignments, and progress tracking.',
    features: ['Course Management', 'Student Dashboard', 'Assignments', 'Grading System', 'Stripe Payments', 'Video Hosting'],
    challenges: ['Video streaming', 'Progress tracking accuracy', 'Scalability'],
  },
  {
    id: 13,
    slug: 'weather-app',
    title: 'Weather Application',
    description: 'Real-time weather app with detailed forecasts, severe weather alerts, and interactive weather maps.',
    category: 'frontend',
    tech: ['React', 'OpenWeatherMap API', 'Mapbox', 'Chart.js', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?w=500&h=500&fit=crop',
    link: 'https://weather-app-demo.vercel.app',
    github: 'https://github.com/allisonfezyy/weather-app',
    linesOfCode: 4500,
    yearBuilt: 2023,
    readme: 'A beautiful weather application with real-time data, forecasts, and interactive maps using OpenWeatherMap API.',
    features: ['Real-time Weather', 'Detailed Forecast', 'Weather Alerts', 'Interactive Maps', 'Location Search', 'Weather History'],
    challenges: ['API integration', 'Real-time updates', 'Map rendering'],
  },
  {
    id: 14,
    slug: 'job-board',
    title: 'Job Board Platform',
    description: 'Job listing platform with advanced search, application tracking, and employer dashboard.',
    category: 'fullstack',
    tech: ['Next.js', 'Node.js', 'PostgreSQL', 'TypeScript', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=500&fit=crop',
    link: 'https://job-board-demo.vercel.app',
    github: 'https://github.com/allisonfezyy/job-board',
    linesOfCode: 10500,
    yearBuilt: 2023,
    readme: 'A comprehensive job board platform with advanced search, application tracking, and employer dashboard.',
    features: ['Job Listings', 'Advanced Search', 'Application Tracking', 'Employer Dashboard', 'Saved Jobs', 'Company Profiles'],
    challenges: ['Search optimization', 'Application workflow', 'Scaling'],
  },
  {
    id: 15,
    slug: 'code-review-tool',
    title: 'Code Review & Collaboration Tool',
    description: 'Modern code review platform with real-time collaboration, code highlighting, and integrated commenting.',
    category: 'fullstack',
    tech: ['Next.js', 'WebSockets', 'PostgreSQL', 'TypeScript', 'Prism.js'],
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=500&fit=crop',
    link: 'https://code-review-tool-demo.vercel.app',
    github: 'https://github.com/allisonfezyy/code-review-tool',
    linesOfCode: 9200,
    yearBuilt: 2024,
    readme: 'A modern code review platform with real-time collaboration features and syntax highlighting.',
    features: ['Code Highlighting', 'Real-time Collaboration', 'Line Comments', 'GitHub Integration', 'Review Dashboard', 'Notifications'],
    challenges: ['Real-time synchronization', 'Code parsing', 'Performance with large files'],
  },
]
// Hero images and site config
export const siteConfig = {
  hero: {
    mainImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=800&fit=crop', // Main professional photo
    featuredImages: [
      'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&h=200&fit=crop', // Small image 1
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&h=200&fit=crop', // Small image 2
    ],
    linesOfCode: '150K+',
  }
}

// Contact information
export const contactInfo = {
  email: 'allisonfezyy@gmail.com',
  phone: '+2349066486040',
  whatsapp: '+2349066486040',
  instagram: 'https://www.instagram.com/one.busy.human.being',
  github: 'https://github.com/allisonfezyy',
}

// Experience and education data
export const experience = {
  yearsInDevelopment: 4,
  totalLinesOfCode: 150000,
  projectsCompleted: 15,
  educationTimeline: [
    {
      year: 2023,
      level: '100L',
      milestone: 'Started Law School Journey',
      description: 'Began studying law while deepening web development skills',
    },
    {
      year: 2024,
      level: '200L',
      milestone: 'Advanced to 200 Level',
      description: 'Took advanced law courses, completed multiple fullstack projects',
    },
    {
      year: 2026,
      level: '300L',
      milestone: 'Currently in 300 Level',
      description: 'Pursuing accounting studies alongside law and web development',
    },
  ],
}
